serviceName: product_core_api

http:
  port: :8081
  development: true
  basePath: /api/v1
  productsPath: /api/v1/products
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
logger:
  level: debug
  devMode: false
  encoder: json
grpc:
  readerServicePort: 5003
rest:
  categoryServicePath: "http://localhost:9001/api/categories"
kafka:
  brokers: [ "localhost:9092" ]
  groupID: product_core_writer_api_consumer
  initTopics: true
kafkaTopics:
  productCreate:
    topicName: product_create
    partitions: 2
    replicationFactor: 1
  productDelete:
    topicName: product_delete
    partitions: 2
    replicationFactor: 1
  productUpdate:
    topicName: product_update
    partitions: 2
    replicationFactor: 1
  productDeactivate:
    topicName: product_deactivate
    partitions: 2
    replicationFactor: 1
prometheus:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10