// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/reader_service/product_reader.proto

package reader_service

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductReaderServiceClient is the client API for ProductReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductReaderServiceClient interface {
	GetProductByID(ctx context.Context, in *GetProductByIDReq, opts ...grpc.CallOption) (*GetProductByIDRes, error)
}

type productReaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductReaderServiceClient(cc grpc.ClientConnInterface) ProductReaderServiceClient {
	return &productReaderServiceClient{cc}
}

func (c *productReaderServiceClient) GetProductByID(ctx context.Context, in *GetProductByIDReq, opts ...grpc.CallOption) (*GetProductByIDRes, error) {
	out := new(GetProductByIDRes)
	err := c.cc.Invoke(ctx, "/productReader.ProductReaderService/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductReaderServiceServer is the server API for ProductReaderService service.
// for forward compatibility
type ProductReaderServiceServer interface {
	GetProductByID(context.Context, *GetProductByIDReq) (*GetProductByIDRes, error)
}

func RegisterProductReaderServiceServer(s grpc.ServiceRegistrar, srv ProductReaderServiceServer) {
	s.RegisterService(&ProductReaderService_ServiceDesc, srv)
}

func _ProductReaderService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReaderServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productReader.ProductReaderService/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReaderServiceServer).GetProductByID(ctx, req.(*GetProductByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductReaderService_ServiceDesc is the grpc.ServiceDesc for ProductReaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductReaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productReader.ProductReaderService",
	HandlerType: (*ProductReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductByID",
			Handler:    _ProductReaderService_GetProductByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reader_service/product_reader.proto",
}
