// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafka.proto

package kafkaMessages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductCreate struct {
	ProductID            string          `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Brand                int32           `protobuf:"varint,4,opt,name=Brand,proto3" json:"Brand,omitempty"`
	Price                float32         `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity             int32           `protobuf:"varint,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	CategoryID           string          `protobuf:"bytes,7,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	ProductImages        []*ProductImage `protobuf:"bytes,8,rep,name=productImages,proto3" json:"productImages,omitempty"`
	Active               bool            `protobuf:"varint,9,opt,name=Active,proto3" json:"Active,omitempty"`
	CreatedAt            string          `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string          `protobuf:"bytes,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            string          `protobuf:"bytes,12,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProductCreate) Reset()         { *m = ProductCreate{} }
func (m *ProductCreate) String() string { return proto.CompactTextString(m) }
func (*ProductCreate) ProtoMessage()    {}
func (*ProductCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_68928ed13de9fb92, []int{0}
}

func (m *ProductCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCreate.Unmarshal(m, b)
}
func (m *ProductCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCreate.Marshal(b, m, deterministic)
}
func (m *ProductCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCreate.Merge(m, src)
}
func (m *ProductCreate) XXX_Size() int {
	return xxx_messageInfo_ProductCreate.Size(m)
}
func (m *ProductCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCreate.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCreate proto.InternalMessageInfo

func (m *ProductCreate) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ProductCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductCreate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductCreate) GetBrand() int32 {
	if m != nil {
		return m.Brand
	}
	return 0
}

func (m *ProductCreate) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductCreate) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *ProductCreate) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

func (m *ProductCreate) GetProductImages() []*ProductImage {
	if m != nil {
		return m.ProductImages
	}
	return nil
}

func (m *ProductCreate) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *ProductCreate) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ProductCreate) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ProductCreate) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type ProductImage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProductID            string   `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductImage) Reset()         { *m = ProductImage{} }
func (m *ProductImage) String() string { return proto.CompactTextString(m) }
func (*ProductImage) ProtoMessage()    {}
func (*ProductImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_68928ed13de9fb92, []int{1}
}

func (m *ProductImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductImage.Unmarshal(m, b)
}
func (m *ProductImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductImage.Marshal(b, m, deterministic)
}
func (m *ProductImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductImage.Merge(m, src)
}
func (m *ProductImage) XXX_Size() int {
	return xxx_messageInfo_ProductImage.Size(m)
}
func (m *ProductImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductImage.DiscardUnknown(m)
}

var xxx_messageInfo_ProductImage proto.InternalMessageInfo

func (m *ProductImage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductImage) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func init() {
	proto.RegisterType((*ProductCreate)(nil), "ProductCreate")
	proto.RegisterType((*ProductImage)(nil), "ProductImage")
}

func init() { proto.RegisterFile("kafka.proto", fileDescriptor_68928ed13de9fb92) }

var fileDescriptor_68928ed13de9fb92 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x6b, 0xb3, 0x40,
	0x10, 0x86, 0xd1, 0x44, 0x3f, 0x1d, 0x23, 0x1f, 0x2c, 0xa5, 0x0c, 0xa5, 0x94, 0x25, 0x27, 0x4f,
	0x39, 0x34, 0x7f, 0xa0, 0x49, 0xbc, 0xe4, 0xd0, 0x62, 0x85, 0x5e, 0x7a, 0xdb, 0xea, 0x34, 0x48,
	0x1a, 0x95, 0x75, 0x53, 0xc8, 0xdf, 0xee, 0x2f, 0x28, 0xbb, 0x2b, 0x1b, 0x7b, 0xdb, 0xf7, 0x79,
	0x16, 0x9d, 0x7d, 0x07, 0x92, 0xa3, 0xf8, 0x3c, 0x8a, 0x55, 0x2f, 0x3b, 0xd5, 0x2d, 0x7f, 0x7c,
	0x48, 0x0b, 0xd9, 0xd5, 0xe7, 0x4a, 0xed, 0x24, 0x09, 0x45, 0xec, 0x1e, 0xe2, 0x11, 0xec, 0x73,
	0xf4, 0xb8, 0x97, 0xc5, 0xe5, 0x15, 0x30, 0x06, 0xf3, 0x17, 0x71, 0x22, 0xf4, 0x8d, 0x30, 0x67,
	0xc6, 0x21, 0xc9, 0x69, 0xa8, 0x64, 0xd3, 0xab, 0xa6, 0x6b, 0x71, 0x66, 0xd4, 0x14, 0xb1, 0x1b,
	0x08, 0xb6, 0x52, 0xb4, 0x35, 0xce, 0xb9, 0x97, 0x05, 0xa5, 0x0d, 0x9a, 0x16, 0xb2, 0xa9, 0x08,
	0x03, 0xee, 0x65, 0x7e, 0x69, 0x03, 0xbb, 0x83, 0xe8, 0xf5, 0x2c, 0x5a, 0xd5, 0xa8, 0x0b, 0x86,
	0xe6, 0xba, 0xcb, 0xec, 0x01, 0x60, 0x27, 0x14, 0x1d, 0x3a, 0x79, 0xd9, 0xe7, 0xf8, 0xcf, 0xfc,
	0x68, 0x42, 0xd8, 0x1a, 0xd2, 0x7e, 0x1c, 0xf5, 0x24, 0x0e, 0x34, 0x60, 0xc4, 0x67, 0x59, 0xf2,
	0x98, 0xae, 0x8a, 0x09, 0x2d, 0xff, 0xde, 0x61, 0xb7, 0x10, 0x6e, 0x2a, 0xd5, 0x7c, 0x13, 0xc6,
	0xdc, 0xcb, 0xa2, 0x72, 0x4c, 0xba, 0x08, 0x5b, 0x49, 0xbd, 0x51, 0x08, 0xb6, 0x08, 0x07, 0xb4,
	0x7d, 0xeb, 0xeb, 0xd1, 0x26, 0xd6, 0x3a, 0xa0, 0x6d, 0x4e, 0x5f, 0x64, 0xed, 0xc2, 0x5a, 0x07,
	0x96, 0x4f, 0xb0, 0x98, 0x0e, 0xa4, 0x4b, 0x6d, 0x75, 0xa9, 0xb6, 0x6d, 0x73, 0xd6, 0x5f, 0xe8,
	0xdd, 0x1a, 0x6c, 0xdb, 0x57, 0xb0, 0xfd, 0xff, 0x9e, 0x9a, 0x2d, 0x3e, 0xd3, 0x30, 0xe8, 0x47,
	0x7c, 0x84, 0x66, 0x9d, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x75, 0xc2, 0x61, 0xdd,
	0x01, 0x00, 0x00,
}
